---
# Container-based Nginx proxy setup
- name: Create www-data user (if not exists)
  user:
    name: www-data
    system: true
    shell: /bin/false
    home: /var/www
    create_home: false
    state: present

- name: Create Nginx configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0755'
  loop:
    - "{{ shared_data_path }}/nginx/config"
    - /var/www/html/.well-known/acme-challenge

- name: Deploy containerized Nginx configuration (HTTP-only initially)
  template:
    src: nginx-container.conf.j2
    dest: "{{ shared_data_path }}/nginx/config/default.conf"
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0644'

- name: Open firewall for HTTP and HTTPS
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - '80'
    - '443'
  when: ansible_os_family == "Debian"