---
# Global variables for all environments
ansible_python_interpreter: /usr/bin/python3

# Security settings
firewall_enabled: true
fail2ban_enabled: true
ssh_password_authentication: false
ssh_permit_root_login: false

# SSL/TLS settings
ssl_provider: letsencrypt
ssl_email: "admin@{{ beryl3_app.domain | default('beryl3-stage.mdubiel.org') }}"
ssl_staging: true  # Use Let's Encrypt staging for testing

# Backup configuration
backup_enabled: true
backup_retention_days: 30
backup_remote_enabled: false  # Enable when remote storage is configured

# Monitoring defaults
monitoring_enabled: true
log_retention_days: 14
metrics_retention_days: 30

# System packages that should be installed on all servers
common_packages:
  - curl
  - wget
  - git
  - htop
  - tree
  - jq
  - unzip
  - certbot
  - python3-certbot-nginx
  - fail2ban
  - ufw
  - logrotate

# Docker settings (if using containerization)
docker_enabled: false
docker_compose_version: "2.20.0"

# Node.js settings (for Tailwind CSS build)
nodejs_version: "18"
npm_packages:
  - "@tailwindcss/cli@next"

# Shared infrastructure paths
shared_data_path: "/opt/shared"

# Shared services configuration
shared_services:
  prometheus:
    port: 9090
    retention_time: "30d"
  grafana:
    port: 3000
    admin_user: "admin"
    admin_password: "grafana123"
  loki:
    port: 3100
  alertmanager:
    port: 9093
  node_exporter:
    port: 9100
  promtail:
    port: 9080

# Application deployment settings
beryl3_app:
  domain: "beryl3-stage.mdubiel.org"
  registry_url: "192.168.1.14:5000"
  registry_namespace: "mdubiel.org"
  image_name: "beryl3-webapp"
  app_port: 8000

# Vault variables (override in vault.yml or environment)
vault_postgres_password: "beryl3_secure_pass_change_me"
vault_django_secret_key: "django-insecure-staging-key-please-change-in-production"
vault_django_admin_password: "admin123"