---
# =====================================
# Application Management Playbook  
# =====================================
# Manages beryl3 application: webapp, email worker, postgres, redis
# Separate from infrastructure services

- name: Manage Beryl3 Application
  hosts: staging
  become: true
  gather_facts: true
  
  vars:
    app_action: "{{ action | default('deploy') }}"  # deploy, start, stop, restart
    app_name: "beryl3"
    app_domain: "beryl3.staging.mdubiel.org"
    app_port: "8000"
    app_root: "/opt/beryl3"
    postgres_db: "beryl3"
    postgres_user: "beryl3_user"
    postgres_password: "{{ vault_postgres_password | default('beryl3_secure_pass') }}"
    
    # Resend configuration
    resend_api_key: "{{ vault_resend_api_key | default(lookup('env', 'RESEND_API_KEY')) | default('re_123456789_YourResendAPIKeyHere') }}"
    
  pre_tasks:
    - name: Validate action parameter
      fail:
        msg: "Invalid action: {{ app_action }}. Must be one of: deploy, start, stop, restart"
      when: app_action not in ['deploy', 'start', 'stop', 'restart']
    
    - name: Display application action
      debug:
        msg: "Application Action: {{ app_action | upper }} for {{ app_name }}"

  tasks:
    - name: Deploy beryl3 application
      include_tasks: tasks/app-deploy.yml
      when: app_action == 'deploy'
      
    - name: Start beryl3 application
      include_tasks: tasks/app-start.yml
      when: app_action == 'start'
      
    - name: Stop beryl3 application
      include_tasks: tasks/app-stop.yml
      when: app_action == 'stop'
      
    - name: Restart beryl3 application
      include_tasks: tasks/app-restart.yml
      when: app_action == 'restart'

  post_tasks:
    - name: Verify application status
      include_tasks: tasks/app-verify.yml
      when: app_action in ['deploy', 'start', 'restart']