---
# =====================================
# Infrastructure Management Playbook
# =====================================
# Manages core infrastructure: nginx, grafana, loki, prometheus, monitoring tools, registry
# Separate from application deployment

- name: Manage Infrastructure Services  
  hosts: staging
  become: true
  gather_facts: true
  
  vars:
    infra_action: "{{ action | default('deploy') }}"  # deploy, start, stop, restart
  
  pre_tasks:
    - name: Validate action parameter
      fail:
        msg: "Invalid action: {{ infra_action }}. Must be one of: deploy, start, stop, restart"
      when: infra_action not in ['deploy', 'start', 'stop', 'restart']
    
    - name: Display infrastructure action
      debug:
        msg: "Infrastructure Action: {{ infra_action | upper }}"

  tasks:
    - name: Deploy infrastructure services
      include_tasks: tasks/infra-deploy.yml
      when: infra_action == 'deploy'
      
    - name: Start infrastructure services
      include_tasks: tasks/infra-start.yml 
      when: infra_action == 'start'
      
    - name: Stop infrastructure services
      include_tasks: tasks/infra-stop.yml
      when: infra_action == 'stop'
      
    - name: Restart infrastructure services
      include_tasks: tasks/infra-restart.yml
      when: infra_action == 'restart'

  post_tasks:
    - name: Verify infrastructure status
      include_tasks: tasks/infra-verify.yml
      when: infra_action in ['deploy', 'start', 'restart']