services:
  postgres:
    image: postgres:15
    container_name: beryl3_postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_USER}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  inbucket:
    image: inbucket/inbucket:latest
    container_name: beryl3_inbucket
    ports:
      - "${INBUCKET_WEB_PORT}:9000"
      - "${INBUCKET_SMTP_PORT}:2500"
    restart: unless-stopped

volumes:
  postgres_data:
