---
# Security role handlers
- name: reload ufw
  systemd:
    name: ufw
    state: reloaded

- name: restart ssh
  systemd:
    name: ssh
    state: restarted
  when: ansible_os_family == "Debian"

- name: restart ssh
  systemd:
    name: sshd
    state: restarted
  when: ansible_os_family in ["RedHat", "Archlinux"]