---
# Security and firewall configuration
- name: Install UFW firewall (if not already installed)
  package:
    name: ufw
    state: present

- name: Reset UFW to defaults
  ufw:
    state: reset
  notify: reload ufw

- name: Set UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify: reload ufw

- name: Allow SSH access
  ufw:
    rule: allow
    port: '22'
    proto: tcp
    comment: 'SSH access'

- name: Allow HTTP traffic
  ufw:
    rule: allow
    port: '80'
    proto: tcp
    comment: 'HTTP traffic'

- name: Allow HTTPS traffic
  ufw:
    rule: allow
    port: '443'
    proto: tcp
    comment: 'HTTPS traffic'

- name: Allow monitoring ports (internal network only)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    src: '192.168.0.0/16'
    comment: 'Monitoring services'
  loop:
    - '3000'  # Grafana
    - '9090'  # Prometheus
    - '9100'  # Node Exporter

- name: Enable UFW
  ufw:
    state: enabled

- name: Configure SSH security
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
    backup: true
  loop:
    - { regex: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
    - { regex: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regex: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
    - { regex: '^#?Port', line: 'Port 22' }
    - { regex: '^#?Protocol', line: 'Protocol 2' }
  notify: restart ssh

- name: Set file permissions for sensitive files
  file:
    path: "{{ item }}"
    mode: '0600'
    owner: root
    group: root
  loop:
    - /etc/ssh/sshd_config
    - /etc/sudoers.d/ansible
  ignore_errors: true