# Generated by Django 5.2 on 2025-06-23 14:06

import django.db.models.deletion
import nanoid_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    nanoid_field.fields.NanoidField(
                        alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-",
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("User Joined", "User Joined"),
                            ("Collection Created", "Collection Created"),
                            ("Collection Deleted", "Collection Deleted"),
                            ("Item Reserved", "Item Reserved"),
                        ],
                        max_length=50,
                        verbose_name="Action Verb",
                    ),
                ),
                (
                    "target_repr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The user whose timeline this event belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recent Activity",
                "verbose_name_plural": "Recent Activities",
                "ordering": ["-created"],
            },
        ),
    ]
