# Generated by Django 5.2 on 2025-06-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_recentactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Visible only to me"),
                    ("UNLISTED", "Shared with link"),
                    ("PUBLIC", "Public"),
                ],
                db_index=True,
                default="PRIVATE",
                max_length=10,
                verbose_name="Visibility",
            ),
        ),
    ]
