# Generated by Django 5.2 on 2025-06-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_collection_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="recentactivity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="name",
            field=models.CharField(
                choices=[
                    ("USER_JOINED", "User Joined"),
                    ("COLLECTION_CREATED", "Collection Created"),
                    ("COLLECTION_DELETED", "Collection Deleted"),
                    ("ITEM_RESERVED", "Item Reserved"),
                ],
                max_length=50,
                verbose_name="Action Verb",
            ),
        ),
    ]
