# Generated by Django 5.2 on 2025-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_recentactivity_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="reserved",
            field=models.BooleanField(default=False, verbose_name="Reserved"),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="reserved_by_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Reserved By Email"
            ),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="reserved_by_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Reserved By Name"
            ),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="reserved_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Reserved Date"
            ),
        ),
    ]
