# Generated by Django 5.2 on 2025-07-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_collectionitem_reserved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionitem",
            name="reserved",
        ),
    ]
