# Generated by Django 5.2 on 2025-07-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_remove_collectionitem_reserved"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="is_favorite",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is Favorite"
            ),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="name",
            field=models.CharField(
                choices=[
                    ("USER_JOINED", "User Joined"),
                    ("COLLECTION_CREATED", "Collection Created"),
                    ("COLLECTION_DELETED", "Collection Deleted"),
                    ("ITEM_ADDED", "Item Added"),
                    ("ITEM_WANTED", "Item Wanted"),
                    ("ITEM_ORDERED", "Item Ordered"),
                    ("ITEM_RESERVED", "Item Reserved"),
                    ("ITEM_LENT", "Item Lent"),
                    ("ITEM_PREVIOUSLY_OWNED", "Item Previously Owned"),
                    ("ITEM_REMOVED", "Item Removed"),
                    ("ITEM_FAVORITED", "Item Favorited"),
                    ("ITEM_UNFAVORITED", "Item Unfavorited"),
                ],
                max_length=50,
                verbose_name="Action Verb",
            ),
        ),
    ]
