# Generated by Django 5.2 on 2025-07-18 19:55

import django.db.models.deletion
import nanoid_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_collectionitem_is_favorite_alter_recentactivity_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="attributes",
            field=models.JSONField(blank=True, default=dict, verbose_name="Attributes"),
        ),
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    nanoid_field.fields.NanoidField(
                        alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-",
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Display Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Lucide Icon Name",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Type",
                "verbose_name_plural": "Item Types",
                "ordering": ["display_name"],
            },
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="item_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="web.itemtype",
                verbose_name="Item Type",
            ),
        ),
        migrations.CreateModel(
            name="ItemAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    nanoid_field.fields.NanoidField(
                        alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-",
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Display Name"),
                ),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("LONG_TEXT", "Long Text"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                            ("URL", "URL"),
                            ("BOOLEAN", "Boolean"),
                            ("CHOICE", "Choice"),
                        ],
                        max_length=20,
                        verbose_name="Attribute Type",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="Required"),
                ),
                (
                    "skip_validation",
                    models.BooleanField(default=False, verbose_name="Skip Validation"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text="For choice fields, provide a list of options",
                        null=True,
                        verbose_name="Choices",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(blank=True, null=True, verbose_name="Help Text"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="web.itemtype",
                        verbose_name="Item Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Attribute",
                "verbose_name_plural": "Item Attributes",
                "ordering": ["item_type", "order", "display_name"],
                "unique_together": {("item_type", "name")},
            },
        ),
    ]
