# Generated by Django 5.2 on 2025-07-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_auto_20250718_1955"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="guest_reservation_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="Guest Reservation Token",
            ),
        ),
    ]
