# Generated by Django 5.2 on 2025-07-23 09:53

import django.db.models.deletion
import nanoid_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_add_guest_reservation_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    nanoid_field.fields.NanoidField(
                        alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-",
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Display Name"),
                ),
                (
                    "url_pattern",
                    models.CharField(
                        help_text="Use * as wildcard, e.g., https://www.amazon.de/*",
                        max_length=255,
                        verbose_name="URL Pattern",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Lucide Icon Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Link Pattern",
                "verbose_name_plural": "Link Patterns",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItemLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    nanoid_field.fields.NanoidField(
                        alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-",
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("is_deleted", models.BooleanField(default=False)),
                ("url", models.URLField(max_length=2000, verbose_name="URL")),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Display Name",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="web.collectionitem",
                        verbose_name="Item",
                    ),
                ),
                (
                    "link_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="links",
                        to="web.linkpattern",
                        verbose_name="Link Pattern",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Item Link",
                "verbose_name_plural": "Collection Item Links",
                "ordering": ["item", "order", "display_name"],
            },
        ),
    ]
