# Generated by Django 5.2 on 2025-08-21 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_mediafile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date Time"
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Function"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                        verbose_name="Level",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action. NULL for anonymous users.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Activity",
                "verbose_name_plural": "Application Activities",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created", "level"],
                        name="web_applica_created_187127_idx",
                    ),
                    models.Index(
                        fields=["user", "-created"],
                        name="web_applica_user_id_7e5bde_idx",
                    ),
                    models.Index(
                        fields=["function_name", "-created"],
                        name="web_applica_functio_8162e9_idx",
                    ),
                ],
            },
        ),
    ]
