# Generated by Django 5.2 on 2025-08-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_applicationactivity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recentactivity",
            name="description",
        ),
        migrations.RemoveField(
            model_name="recentactivity",
            name="target_repr",
        ),
        migrations.AddField(
            model_name="recentactivity",
            name="icon",
            field=models.CharField(
                default="activity", max_length=50, verbose_name="Lucide Icon Name"
            ),
        ),
        migrations.AddField(
            model_name="recentactivity",
            name="message",
            field=models.TextField(
                default="Activity message", verbose_name="Activity Message"
            ),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="details",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Additional Details"
            ),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
    ]
