# Generated by Django 5.2 on 2025-08-21 17:08

import django.db.models.deletion
import nanoid_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_remove_recentactivity_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    nanoid_field.fields.NanoidField(
                        alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-",
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The primary image shown in collection displays",
                        verbose_name="Default Image",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order for thumbnail display (0-2)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="web.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_images",
                        to="web.mediafile",
                        verbose_name="Media File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Image",
                "verbose_name_plural": "Collection Images",
                "ordering": ["collection", "order"],
                "indexes": [
                    models.Index(
                        fields=["collection", "is_default"],
                        name="web_collect_collect_cdc40d_idx",
                    ),
                    models.Index(
                        fields=["collection", "order"],
                        name="web_collect_collect_daf5c5_idx",
                    ),
                ],
                "unique_together": {("collection", "media_file")},
            },
        ),
        migrations.CreateModel(
            name="CollectionItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    nanoid_field.fields.NanoidField(
                        alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-",
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The primary image shown in item displays",
                        verbose_name="Default Image",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order for thumbnail display (0-2)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="web.collectionitem",
                        verbose_name="Collection Item",
                    ),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_images",
                        to="web.mediafile",
                        verbose_name="Media File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Item Image",
                "verbose_name_plural": "Collection Item Images",
                "ordering": ["item", "order"],
                "indexes": [
                    models.Index(
                        fields=["item", "is_default"],
                        name="web_collect_item_id_ae4644_idx",
                    ),
                    models.Index(
                        fields=["item", "order"], name="web_collect_item_id_090f9d_idx"
                    ),
                ],
                "unique_together": {("item", "media_file")},
            },
        ),
    ]
