# Generated by Django 5.2 on 2025-08-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_collectionimage_collectionitemimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recentactivity",
            name="details",
        ),
        migrations.RemoveField(
            model_name="recentactivity",
            name="subject",
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="icon",
            field=models.CharField(
                default="activity",
                help_text="Must be a valid Lucide icon name",
                max_length=50,
                verbose_name="Lucide Icon Name",
            ),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="message",
            field=models.TextField(
                help_text="Markdown supported for highlights",
                verbose_name="Activity Message",
            ),
        ),
    ]
