# Generated by Django 5.2 on 2025-09-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_simplify_recent_activity"),
    ]

    operations = [
        # Drop the ApplicationActivity table since we're replacing it with standard logging
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS web_applicationactivity;",
            reverse_sql="-- Cannot reverse this migration - ApplicationActivity table structure would need to be recreated manually",
        ),
    ]
