# Generated by Django 5.2 on 2025-09-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0018_remove_application_activity"),
    ]

    operations = [
        # ApplicationActivity table was already dropped in migration 0018
        # This migration just removes the model definition from Django's state
        migrations.RunSQL(
            sql="SELECT 1 -- Table already dropped in previous migration",
            reverse_sql="SELECT 1 -- Cannot reverse - table was already dropped",
            state_operations=[
                migrations.DeleteModel(
                    name="ApplicationActivity",
                ),
            ]
        ),
    ]
