# Generated by Django 5.2 on 2025-09-22 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_delete_applicationactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receive_marketing_emails",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, you will receive marketing emails from us",
                        verbose_name="Receive Marketing Emails",
                    ),
                ),
                (
                    "resend_audience_id",
                    models.CharField(
                        blank=True,
                        help_text="Internal ID for tracking in Resend audience",
                        max_length=100,
                        null=True,
                        verbose_name="Resend Audience ID",
                    ),
                ),
                (
                    "marketing_email_subscribed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Marketing Email Subscribed At",
                    ),
                ),
                (
                    "marketing_email_unsubscribed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Marketing Email Unsubscribed At",
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(
                        blank=True,
                        help_text="Secure token for unsubscribe links",
                        max_length=64,
                        null=True,
                        verbose_name="Unsubscribe Token",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
