# Generated by Django 5.2 on 2025-09-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0020_add_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="Optional nickname to display instead of your first name",
                max_length=50,
                null=True,
                verbose_name="Nickname",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="use_nickname",
            field=models.BooleanField(
                default=False,
                help_text="If checked, your nickname will be used instead of your first name",
                verbose_name="Use Nickname for Display",
            ),
        ),
    ]
