# Generated by Django 5.2 on 2025-09-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_add_nickname_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="resend_is_subscribed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the email is actually in the Resend audience (last known status)",
                verbose_name="Actually Subscribed in Resend",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resend_last_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When we last checked the status with Resend",
                null=True,
                verbose_name="Last Resend Check",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resend_sync_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("synced", "Synced"),
                    ("out_of_sync", "Out of Sync"),
                    ("error", "Error"),
                ],
                default="unknown",
                help_text="Current synchronization status with Resend audience",
                max_length=20,
                verbose_name="Resend Sync Status",
            ),
        ),
    ]
