# Generated by Django 5.2 on 2025-09-25 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_userprofile_resend_is_subscribed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="content_moderation_checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Content Check"
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="content_moderation_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed results from content moderation analysis",
                verbose_name="Content Moderation Details",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="content_moderation_score",
            field=models.FloatField(
                blank=True,
                help_text="AI confidence score for inappropriate content (0.0-1.0)",
                null=True,
                verbose_name="Content Moderation Score",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="content_moderation_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("APPROVED", "Approved"),
                    ("FLAGGED", "Flagged as Inappropriate"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="Content Moderation Status",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="content_ban_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for content-related ban",
                null=True,
                verbose_name="Content Ban Reason",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="content_banned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Content Banned At"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="content_moderation_violations",
            field=models.IntegerField(
                default=0,
                help_text="Number of inappropriate content violations",
                verbose_name="Content Violations Count",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_content_banned",
            field=models.BooleanField(
                default=False,
                help_text="User is banned due to content policy violations",
                verbose_name="Content Banned",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_violation_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Violation"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["content_moderation_status"],
                name="web_mediafi_content_e4b341_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                fields=["content_moderation_checked_at"],
                name="web_mediafi_content_205561_idx",
            ),
        ),
    ]
