# Generated by Django 5.2 on 2025-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_mediafile_content_moderation_checked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="content_moderation_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("APPROVED", "Approved"),
                    ("FLAGGED", "Flagged"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="Content Moderation Status",
            ),
        ),
    ]
