# Generated by Django 5.2 on 2025-10-04 19:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_alter_mediafile_content_moderation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When metrics were collected"
                    ),
                ),
                (
                    "collection_date",
                    models.DateField(
                        help_text="Date of metrics snapshot (one per day)", unique=True
                    ),
                ),
                (
                    "collection_duration_seconds",
                    models.IntegerField(
                        default=0, help_text="How long collection took in seconds"
                    ),
                ),
                (
                    "total_users",
                    models.IntegerField(default=0, help_text="Total registered users"),
                ),
                (
                    "active_users_24h",
                    models.IntegerField(
                        default=0, help_text="Users active in last 24 hours"
                    ),
                ),
                (
                    "active_users_7d",
                    models.IntegerField(
                        default=0, help_text="Users active in last 7 days"
                    ),
                ),
                (
                    "active_users_30d",
                    models.IntegerField(
                        default=0, help_text="Users active in last 30 days"
                    ),
                ),
                (
                    "new_users_24h",
                    models.IntegerField(
                        default=0, help_text="New users in last 24 hours"
                    ),
                ),
                (
                    "new_users_7d",
                    models.IntegerField(
                        default=0, help_text="New users in last 7 days"
                    ),
                ),
                (
                    "new_users_30d",
                    models.IntegerField(
                        default=0, help_text="New users in last 30 days"
                    ),
                ),
                (
                    "total_collections",
                    models.IntegerField(default=0, help_text="Total collections"),
                ),
                (
                    "total_items",
                    models.IntegerField(
                        default=0, help_text="Total items across all collections"
                    ),
                ),
                (
                    "collections_private",
                    models.IntegerField(
                        default=0, help_text="Private collections count"
                    ),
                ),
                (
                    "collections_public",
                    models.IntegerField(
                        default=0, help_text="Public collections count"
                    ),
                ),
                (
                    "collections_unlisted",
                    models.IntegerField(
                        default=0, help_text="Unlisted collections count"
                    ),
                ),
                (
                    "items_in_collection",
                    models.IntegerField(
                        default=0, help_text="Items with status: In Collection"
                    ),
                ),
                (
                    "items_wanted",
                    models.IntegerField(
                        default=0, help_text="Items with status: Wanted"
                    ),
                ),
                (
                    "items_reserved",
                    models.IntegerField(
                        default=0, help_text="Items with status: Reserved"
                    ),
                ),
                (
                    "items_ordered",
                    models.IntegerField(
                        default=0, help_text="Items with status: Ordered"
                    ),
                ),
                (
                    "items_lent",
                    models.IntegerField(default=0, help_text="Items with status: Lent"),
                ),
                (
                    "items_previously_owned",
                    models.IntegerField(
                        default=0, help_text="Items with status: Previously Owned"
                    ),
                ),
                (
                    "items_sold",
                    models.IntegerField(default=0, help_text="Items with status: Sold"),
                ),
                (
                    "items_given_away",
                    models.IntegerField(
                        default=0, help_text="Items with status: Given Away"
                    ),
                ),
                (
                    "item_types_count",
                    models.IntegerField(
                        default=0, help_text="Total item types defined"
                    ),
                ),
                (
                    "item_type_distribution",
                    models.JSONField(
                        default=dict,
                        help_text="Distribution of items by type {type_name: count}",
                    ),
                ),
                (
                    "total_attributes",
                    models.IntegerField(
                        default=0, help_text="Total attribute definitions"
                    ),
                ),
                (
                    "attribute_usage",
                    models.JSONField(
                        default=dict,
                        help_text="Attribute usage statistics {attr_name: count}",
                    ),
                ),
                (
                    "total_links",
                    models.IntegerField(
                        default=0, help_text="Total links in items and collections"
                    ),
                ),
                (
                    "matched_link_patterns",
                    models.IntegerField(
                        default=0, help_text="Links matching defined patterns"
                    ),
                ),
                (
                    "unmatched_link_patterns",
                    models.IntegerField(
                        default=0, help_text="Links not matching any pattern"
                    ),
                ),
                (
                    "link_pattern_distribution",
                    models.JSONField(
                        default=dict,
                        help_text="Link usage by pattern {pattern_name: count}",
                    ),
                ),
                (
                    "total_media_files",
                    models.IntegerField(default=0, help_text="Total media files"),
                ),
                (
                    "total_storage_bytes",
                    models.BigIntegerField(
                        default=0, help_text="Total storage used in bytes"
                    ),
                ),
                (
                    "recent_uploads_24h",
                    models.IntegerField(
                        default=0, help_text="Media files uploaded in last 24h"
                    ),
                ),
                (
                    "recent_uploads_7d",
                    models.IntegerField(
                        default=0, help_text="Media files uploaded in last 7 days"
                    ),
                ),
                (
                    "recent_uploads_30d",
                    models.IntegerField(
                        default=0, help_text="Media files uploaded in last 30 days"
                    ),
                ),
                (
                    "orphaned_files",
                    models.IntegerField(
                        default=0,
                        help_text="Media files not linked to items/collections",
                    ),
                ),
                (
                    "corrupted_files",
                    models.IntegerField(
                        default=0, help_text="Media files that failed integrity check"
                    ),
                ),
                (
                    "storage_by_type",
                    models.JSONField(
                        default=dict,
                        help_text="Storage distribution by file type {ext: bytes}",
                    ),
                ),
                (
                    "total_emails",
                    models.IntegerField(
                        blank=True, help_text="Total emails tracked", null=True
                    ),
                ),
                (
                    "emails_pending",
                    models.IntegerField(
                        blank=True, help_text="Emails pending delivery", null=True
                    ),
                ),
                (
                    "emails_sent",
                    models.IntegerField(
                        blank=True, help_text="Emails successfully sent", null=True
                    ),
                ),
                (
                    "emails_failed",
                    models.IntegerField(
                        blank=True, help_text="Emails that failed to send", null=True
                    ),
                ),
                (
                    "marketing_opt_in",
                    models.IntegerField(
                        blank=True, help_text="Users opted in to marketing", null=True
                    ),
                ),
                (
                    "marketing_opt_out",
                    models.IntegerField(
                        blank=True, help_text="Users opted out of marketing", null=True
                    ),
                ),
                (
                    "emails_synced_resend",
                    models.BooleanField(
                        default=False,
                        help_text="Whether email stats are synced with Resend",
                    ),
                ),
                (
                    "flagged_content",
                    models.IntegerField(
                        default=0, help_text="Content items flagged for review"
                    ),
                ),
                (
                    "pending_review",
                    models.IntegerField(
                        default=0, help_text="Content items pending moderation"
                    ),
                ),
                (
                    "user_violations",
                    models.IntegerField(default=0, help_text="Total user violations"),
                ),
                (
                    "banned_users",
                    models.IntegerField(default=0, help_text="Currently banned users"),
                ),
                (
                    "favorite_items_total",
                    models.IntegerField(default=0, help_text="Total favorited items"),
                ),
                (
                    "items_with_images_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of items with images",
                        max_digits=5,
                    ),
                ),
                (
                    "items_with_attributes_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of items with custom attributes",
                        max_digits=5,
                    ),
                ),
                (
                    "items_with_links_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of items with links",
                        max_digits=5,
                    ),
                ),
                (
                    "avg_attributes_per_item",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average attributes per item",
                        max_digits=5,
                    ),
                ),
                (
                    "avg_items_per_collection",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average items per collection",
                        max_digits=7,
                    ),
                ),
                (
                    "items_created_24h",
                    models.IntegerField(
                        default=0, help_text="Items created in last 24h"
                    ),
                ),
                (
                    "items_created_7d",
                    models.IntegerField(
                        default=0, help_text="Items created in last 7 days"
                    ),
                ),
                (
                    "items_created_30d",
                    models.IntegerField(
                        default=0, help_text="Items created in last 30 days"
                    ),
                ),
                (
                    "collections_created_24h",
                    models.IntegerField(
                        default=0, help_text="Collections created in last 24h"
                    ),
                ),
                (
                    "collections_created_7d",
                    models.IntegerField(
                        default=0, help_text="Collections created in last 7 days"
                    ),
                ),
                (
                    "collections_created_30d",
                    models.IntegerField(
                        default=0, help_text="Collections created in last 30 days"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Metrics",
                "verbose_name_plural": "Daily Metrics",
                "ordering": ["-collection_date"],
                "indexes": [
                    models.Index(
                        fields=["-collection_date"],
                        name="web_dailyme_collect_0f8386_idx",
                    ),
                    models.Index(
                        fields=["collected_at"], name="web_dailyme_collect_189c31_idx"
                    ),
                ],
            },
        ),
    ]
