# Generated by Django 5.2 on 2025-10-05 11:54

import django.db.models.deletion
import nanoid_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_dailymetrics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionItemAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    nanoid_field.fields.NanoidField(
                        alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-",
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "value",
                    models.TextField(
                        help_text="Stored as text, converted to appropriate type on retrieval",
                        verbose_name="Value",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="For multiple values of the same attribute (e.g., multiple authors)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="web.collectionitem",
                        verbose_name="Collection Item",
                    ),
                ),
                (
                    "item_attribute",
                    models.ForeignKey(
                        help_text="The attribute schema this value conforms to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="web.itemattribute",
                        verbose_name="Attribute Definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Item Attribute Value",
                "verbose_name_plural": "Collection Item Attribute Values",
                "ordering": ["item", "item_attribute", "order"],
                "indexes": [
                    models.Index(
                        fields=["item", "item_attribute"],
                        name="web_collect_item_id_5b7c08_idx",
                    ),
                    models.Index(
                        fields=["item", "order"], name="web_collect_item_id_595ad5_idx"
                    ),
                ],
            },
        ),
    ]
