# Generated by Django 5.2 on 2025-10-05 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0026_add_collection_item_attribute_value_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionitemattributevalue",
            options={
                "ordering": ["item", "item_attribute", "value", "created"],
                "verbose_name": "Collection Item Attribute Value",
                "verbose_name_plural": "Collection Item Attribute Values",
            },
        ),
        migrations.RemoveIndex(
            model_name="collectionitemattributevalue",
            name="web_collect_item_id_595ad5_idx",
        ),
        migrations.RemoveField(
            model_name="collectionitemattributevalue",
            name="order",
        ),
        migrations.AddIndex(
            model_name="collectionitemattributevalue",
            index=models.Index(
                fields=["item", "item_attribute", "value"],
                name="web_collect_item_id_b269cb_idx",
            ),
        ),
    ]
