# Generated by Django 5.2 on 2025-10-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0027_remove_order_field_from_attribute_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionitem",
            name="attributes",
        ),
    ]
