# Generated by Django 5.2 on 2025-10-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0028_remove_attributes_json_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="enable_grouping",
            field=models.BooleanField(
                default=False,
                help_text="Group items by shared attribute values",
                verbose_name="Enable Grouping",
            ),
        ),
    ]
