# Generated by Django 5.2 on 2025-10-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0029_collection_enable_grouping"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="grouping_attribute",
            field=models.ForeignKey(
                blank=True,
                help_text="Select which attribute to group items by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grouped_collections",
                to="web.itemattribute",
                verbose_name="Group By Attribute",
            ),
        ),
    ]
