# Generated by Django 5.2 on 2025-10-06 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0030_collection_grouping_attribute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="enable_grouping",
        ),
        migrations.AddField(
            model_name="collection",
            name="group_by",
            field=models.CharField(
                choices=[
                    ("NONE", "No Grouping"),
                    ("ITEM_TYPE", "Item Type"),
                    ("STATUS", "Status"),
                    ("ATTRIBUTE", "Attribute"),
                ],
                default="NONE",
                help_text="Group items by type, status, or attribute",
                max_length=20,
                verbose_name="Group By",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="sort_attribute",
            field=models.ForeignKey(
                blank=True,
                help_text="Select which attribute to sort items by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sorted_collections",
                to="web.itemattribute",
                verbose_name="Sort By Attribute",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="sort_by",
            field=models.CharField(
                choices=[
                    ("NAME", "Name"),
                    ("CREATED", "Date Created"),
                    ("UPDATED", "Date Updated"),
                    ("ATTRIBUTE", "Attribute Value"),
                ],
                default="NAME",
                help_text="Sort items within groups",
                max_length=20,
                verbose_name="Sort By",
            ),
        ),
    ]
