# Generated by Django 5.2 on 2025-10-21 19:05

import django.db.models.deletion
import nanoid_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0031_remove_collection_enable_grouping_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="your_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your personal identifier for this item",
                max_length=100,
                verbose_name="Your ID",
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash",
                    nanoid_field.fields.NanoidField(
                        alphabet="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz-",
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Location Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical location where this item is stored",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="web.location",
                verbose_name="Location",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["created_by", "name"], name="web_locatio_created_d0592f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("created_by", "name")},
        ),
    ]
