# Generated by Django 5.2 on 2025-11-02 14:04

import web.models_user_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_add_location_and_custom_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="Optional nickname for public profile URL (letters, digits, dash, underscore only)",
                max_length=50,
                null=True,
                unique=True,
                validators=[web.models_user_profile.validate_nickname],
                verbose_name="Nickname",
            ),
        ),
    ]
