# Generated by Django 5.2 on 2025-11-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0033_alter_userprofile_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hash",
            field=models.CharField(
                blank=True,
                help_text="Unique hash for public profile URL",
                max_length=10,
                verbose_name="User Hash",
            ),
        ),
    ]
