# Generated by Django 5.2 on 2025-11-02 16:49

from django.db import migrations
from nanoid import generate


def populate_user_profile_hashes(apps, schema_editor):
    """Populate hash field for existing UserProfile records"""
    UserProfile = apps.get_model('web', 'UserProfile')

    # Get all profiles that need hashes
    profiles_to_update = list(UserProfile.objects.filter(hash=''))

    if not profiles_to_update:
        return  # Nothing to do

    # Generate unique hashes for all profiles
    generated_hashes = set()
    for profile in profiles_to_update:
        # Generate unique hash
        while True:
            new_hash = generate(size=10)
            if new_hash not in generated_hashes and not UserProfile.objects.filter(hash=new_hash).exists():
                profile.hash = new_hash
                generated_hashes.add(new_hash)
                break

    # Bulk update in batches of 100 to avoid memory issues
    batch_size = 100
    for i in range(0, len(profiles_to_update), batch_size):
        batch = profiles_to_update[i:i + batch_size]
        UserProfile.objects.bulk_update(batch, ['hash'], batch_size=batch_size)


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear hash field"""
    UserProfile = apps.get_model('web', 'UserProfile')
    UserProfile.objects.all().update(hash='')


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0034_add_user_profile_hash_field"),
    ]

    operations = [
        migrations.RunPython(populate_user_profile_hashes, reverse_populate),
    ]
