# Generated by Django 5.2 on 2025-11-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0035_populate_user_profile_hashes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="hash",
            field=models.CharField(
                blank=True,
                help_text="Unique hash for public profile URL",
                max_length=10,
                unique=True,
                verbose_name="User Hash",
            ),
        ),
    ]
