# Generated by Django 5.2 on 2025-11-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0037_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="collectionitem",
            name="web_collectionitem_collection_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="collectionitem",
            name="web_collectionitem_collection_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="collectionitem",
            name="web_collectionitem_collection_favorite_idx",
        ),
        migrations.RemoveIndex(
            model_name="collectionitem",
            name="web_collectionitem_collection_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="collectionitem",
            name="web_collectionitem_collection_created_desc_idx",
        ),
        migrations.RemoveIndex(
            model_name="collectionitemattributevalue",
            name="web_collectionitemattributevalue_value_idx",
        ),
    ]
