---
# SSL certificate management for container-based nginx
- name: Install Certbot
  package:
    name: 
      - certbot
    state: present

- name: Generate SSL certificate for staging domain
  command: >
    certbot certonly --webroot --webroot-path=/var/www/html
    --email admin@{{ domain_suffix }}
    --agree-tos --no-eff-email
    -d grafana.{{ domain_suffix }}
    -d prometheus.{{ domain_suffix }}
    -d beryl3.{{ domain_suffix }}
    -d monitoring.{{ domain_suffix }}
  register: certbot_result
  failed_when: 
    - certbot_result.rc != 0
    - "'Certificate not yet due for renewal' not in certbot_result.stdout"

- name: Deploy SSL-enabled container Nginx configuration
  template:
    src: nginx-container-ssl.conf.j2
    dest: "{{ shared_data_path }}/nginx/config/default.conf"
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0644'
  notify: restart nginx container

- name: Set up certificate renewal cron job
  cron:
    name: "Renew Let's Encrypt certificates"
    minute: "0"
    hour: "2"
    day: "*"
    month: "*"
    weekday: "*"
    job: "/usr/bin/certbot renew --quiet && cd {{ shared_data_path }} && docker-compose restart nginx-proxy"
    user: root