---
# Restart Infrastructure Containers

- name: Restart infrastructure containers
  community.docker.docker_container:
    name: "{{ item }}"
    state: started
    restart: true
  loop:
    - nginx-proxy
    - docker-registry
    - docker-registry-ui
    - prometheus
    - grafana
    - loki
    - alertmanager
    - node-exporter
    - cadvisor
    - promtail
    - blackbox-exporter
    - nginx-prometheus-exporter
    - adminer
  ignore_errors: true