apiVersion: 1

datasources:
  # Prometheus data source
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    uid: prometheus
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: High
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      
  # Loki data source for logs
  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
    uid: loki
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"