/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './templates/**/*.html',
    './src/**/*.css',
    './static/**/*.js',
    './**/*.py',
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        'beryl-admin': {
          'primary': '#74b9ff',
          'primary-content': '#ffffff',
          'secondary': '#34495e',
          'secondary-content': '#ecf0f1',
          'accent': '#74b9ff',
          'accent-content': '#ffffff',
          'neutral': '#2c3e50',
          'neutral-content': '#ecf0f1',
          'base-100': '#ffffff',
          'base-200': '#f8f9fa',
          'base-300': '#ecf0f1',
          'base-content': '#2c3e50',
          'info': '#3498db',
          'success': '#74b9ff',
          'warning': '#f39c12',
          'error': '#e74c3c',
        },
        'beryl-navy': {
          'primary': '#34495e',
          'primary-content': '#ffffff',
          'secondary': '#2c3e50',
          'secondary-content': '#ecf0f1',
          'accent': '#74b9ff',
          'accent-content': '#ffffff',
          'neutral': '#2c3e50',
          'neutral-content': '#ecf0f1',
          'base-100': '#ffffff',
          'base-200': '#f8f9fa',
          'base-300': '#ecf0f1',
          'base-content': '#2c3e50',
          'info': '#3498db',
          'success': '#27ae60',
          'warning': '#f39c12',
          'error': '#e74c3c',
        },
      },
      'light',
      'dark',
    ],
    darkTheme: 'beryl-navy',
    base: true,
    styled: true,
    utils: true,
    prefix: '',
    logs: true,
    themeRoot: ':root',
  },
}